### ISSUE TITLE
Failed to download action. 404 (Not Found)

### ISSUE THREAD

**Issue by Mixermachine** [supercharge/redis-github-action#1]
Hy @marcuspoehls 

I'm currently trying to run a test redis server for my nodeJs app.
Sadly the actions throws the following error:
Failed to download action 'https://api.github.com/repos/superchargejs/redis-github-action/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).

After some tries the action fails.

I'm using:
nodeJs: 13.x
redis: 5

but it failed for all versions for me.

Greetings from Munich

Aaron

**Comment by marcuspoehls** [comment]
@Mixermachine Hi Aaron, sorry for this issue. I found two problems in the example of this actions Readme.

Here's a working setup snippet:

```YAML
- name: Redis Server in GitHub Actions
  uses: supercharge/redis-github-action@1.1.0
```

(You must indent the code in your YAML file)


I recently changed the account name from `superchargejs` to `supercharge`. Also the versioning is important. The published releases are fixed and GitHub won't match `v1` to the latest release in the `v1.x` release line.

Hope that helps. Thank you for reporting this issue!

Greetings from Magdeburg 😃
Marcus

**Comment by Mixermachine** [comment]
@marcuspoehls Hi Marcus,
thank you for your snipped.
supercharge/redis-github-action@1.1.0 works :).

Small hands up: On your readme page the name is written with a additional v before the version number (does not work)
-> supercharge/redis-github-action@v1.1.0

Greetings from Munich

Aaron

**Comment by marcuspoehls** [comment]
@Mixermachine Yeah, good to know it works!

Thank you for the heads up. I’ve updated the Readme and removed the `v` prefix.
