### ISSUE TITLE
Custom Redis image

### ISSUE THREAD

**Issue by YaraslauZhylko** [supercharge/redis-github-action#11]
Should it be possible to launch an alternative Redis package like Redis Stack by specifying a custom image name? 🤔 

Potential implementation: #10

**Comment by marcuspoehls** [comment]
@YaraslauZhylko Hey Yaraslau, good idea! Thank you for the pull request 👍 I’ll review the changes, comment or merge it and publish a new release afterwards

**Comment by marcuspoehls** [comment]
I just published version `1.5.0` of this action supporting custom Redis images 😃

**Comment by YaraslauZhylko** [comment]
Thanks!
