### ISSUE TITLE
Make it available to windows-latest images

### ISSUE THREAD

**Issue by guibranco** [supercharge/redis-github-action#12]
Make this action available to `windows-latest` image. Currently only runs on `linux` or `macOS` images

**Comment by geekact** [comment]
Actually, it only works on `linux`

**Comment by marcuspoehls** [comment]
@guibranco @geekact Hey, thanks for pointing that out :) Can you both look into supporting Windows please?

**Comment by marcuspoehls** [comment]
Closing this in the absence of support and feedback. I assume it’s currently not important and not urgent.
