### ISSUE TITLE
Redis Cluster Support

### ISSUE THREAD

**Issue by gaby** [supercharge/redis-github-action#13]
Would it be possible to have a basic 2-3 servers Redis cluster? 🤔

**Comment by marcuspoehls** [comment]
@gaby Hey Juan, good question. I didn't look into Redis clusters yet. And I'm not sure how that works on GitHub Actions runners.

Do you know more about Redis cluster and how to set them up with Docker?

**Comment by gaby** [comment]
@marcuspoehls I found this one last night that seems to be work. 

https://github.com/vishnudxb/redis-cluster

**Comment by gaby** [comment]
@marcuspoehls Up to you, the other action seems to be working fine during our tests.

Having everything under one Action would be ideal for simplicity but yeah.

**Comment by marcuspoehls** [comment]
@gaby Hey Juan, having support for a single Redis node and also for a Redis cluster in this action would be ideal. Then developers could choose the variant based on the app’s setup.

Are you open for submitting a pull request adding Redis cluster support?

**Comment by gaby** [comment]
@marcuspoehls I honestly have no experience doing github actions, else I would have helped with that.

**Comment by marcuspoehls** [comment]
@gaby Ok 👍
