### ISSUE TITLE
Remove redis container on self-hosted runner

### ISSUE THREAD

**Issue by kien-cs** [supercharge/redis-github-action#14]
Hi,

Would you open to add an `--rm` option to the docker run to remove the container? 
https://github.com/supercharge/redis-github-action/blob/main/start-redis.sh#L15

This will help with project that are running on shared self-hosted runner.

Two ways to do this: 
1) Set --rm as the default at the docker run arg
2) Create a new optional args to pass in this option at the action level

Let me know your thought and I'm happy to send in PR.

**Comment by marcuspoehls** [comment]
@kien-cs Hey Kien, that’s great. Yes, I would like to add an `--rm` option to this GitHub Action allowing people to remove a Redis container created by this action from their self-hosted runners 👍 I appreciate your offer to send a pull request. Please go ahead and create the pull request 🙂

**Comment by kien-cs** [comment]
@marcuspoehls thanks for accepting this issue. Here's my proposed PR: https://github.com/supercharge/redis-github-action/pull/15/files . Please help me review. Thank you!

**Comment by marcuspoehls** [comment]
@kien-cs I’ve published version `1.6.0` including the newly added `redis-remove-container` option. Thank you for your contribution, I appreciate it! 🙂

**Comment by marcuspoehls** [comment]
Please send feedback if this option works for you and cleans the container on self-hosted runners :)

**Comment by kien-cs** [comment]
@marcuspoehls all good now. Thank you!

**Comment by marcuspoehls** [comment]
@kien-cs Sweet! 👍
