### ISSUE TITLE
Error: "docker: invalid reference format"

### ISSUE THREAD

**Issue by francislavoie** [supercharge/redis-github-action#3]
See https://github.com/Vectorface/cache/pull/8/checks?check_run_id=1592485519

```
/usr/bin/docker run --name cc4956c4ab57414d304381943ac46fbbdd502f_656d49 --label cc4956 --workdir /github/workspace --rm -e INPUT_REDIS-VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cache/cache":"/github/workspace" cc4956:c4ab57414d304381943ac46fbbdd502f  ""
docker: invalid reference format.
```

Any thoughts? :thinking:

**Comment by marcuspoehls** [comment]
@francislavoie Hey Francis, I think you’re not defining a Redis version in your GitHub Actions workflow file.

Here’s a sample using Redis

**Comment by francislavoie** [comment]
I did actually https://github.com/Vectorface/cache/commit/7f6a103e06939d60c23ac14eb0c22c26b023da67 but oops, just noticed I made a typo with plural `s` 😬 my bad!

**Comment by francislavoie** [comment]
That said, the error could probably be more useful. Maybe this action should validate that the version number looks reasonable (non-empty etc) before trying to run Docker? Would have saved me from this confusion 😅

**Comment by marcuspoehls** [comment]
@francislavoie Yeah definitely, the action should validate the input before starting the Docker container. Would avoid frustration and confusion in case of issues. Thank you for making it obvious 👍
