### ISSUE TITLE
Unable to pass custom redis.conf file

### ISSUE THREAD

**Issue by ChrisMoriarty** [supercharge/redis-github-action#5]
The docs don't seem to show how to pass a custom redis.conf file when starting the server.  Is it possible?

**Comment by marcuspoehls** [comment]
@ChrisMoriarty Hey Chris, it’s currently not possible to define and use a custom Redis config file.

Would be nice if you can send a pull request for that feature :)

**Comment by ChrisMoriarty** [comment]
Thanks for the quick reply, I found another similar tool called actions-setup-redis that does support a conf file.  

https://github.com/marketplace/actions/actions-setup-redis

Alas, I have hit another wall in that I need to run these tests for windows, mac and linux, and currently docker based steps only seem to be supported on Linux.

**Comment by marcuspoehls** [comment]
Yeah, running Docker-based container actions is only supported on Linux hosts. Ok, Thank you for sharing the Redis GitHub Action having support for custom configs 👍
